services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n:/home/node/.n8n
    networks:
      - n8n
    restart: unless-stopped
    environment:
      GENERIC_TIMEZONE: Asia/Shanghai
      TZ: Asia/Shanghai
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: true
      N8N_SECURE_COOKIE: false
      N8N_EDITOR_BASE_URL: http://n8n.wss.qh.cn:5678

      N8N_RUNNERS_ENABLED: true
      N8N_RUNNERS_MODE: external
      N8N_RUNNERS_BROKER_LISTEN_ADDRESS: 0.0.0.0
      N8N_RUNNERS_AUTH_TOKEN: qwertyuiop

      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_USER: postgres
      DB_POSTGRESDB_PASSWORD: postgres
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_SCHEMA: public

  runners:
    image: n8nio/runners
    container_name: n8n-runners
    networks:
      - n8n
    restart: unless-stopped
    depends_on:
      - n8n
    environment:
      N8N_RUNNERS_TASK_BROKER_URI: "http://n8n:5679"
      N8N_RUNNERS_AUTH_TOKEN: qwertyuiop

volumes:
  n8n:
    external: true

networks:
  n8n:
    external: true
