services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
    network_mode: bridge
    restart: unless-stopped
    environment:
      OFFLINE_MODE: true
      HF_HUB_OFFLINE: 1
      RAG_EMBEDDING_MODEL_AUTO_UPDATE: false
      RAG_RERANKING_MODEL_AUTO_UPDATE: false
      WHISPER_MODEL_AUTO_UPDATE: false

volumes:
  open-webui:
    external: true
