services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql
    network_mode: bridge
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  postgres:
    external: true
